### ISSUE TITLE
Types in PHPDoc blocks

### ISSUE THREAD

**Issue by szepeviktor** [brick/ftp#2]
When you expect unexpected data it should be `mixed` instead of `string|resource`.
E.g. in `upload()`

Discovered by @phpstan `phpstan analyze --level=max ./src/`

**Comment by BenMorel** [comment]
I'm not sure why phpstan says this, I'm not expecting *unexpected* data, but any of two well-defined types.

This is in line with upcoming [union types](https://github.com/php/php-rfcs/pull/1) that may well come to PHP 8.

Out of curiosity, are you running phpstan automatically on all recently published packagist packages?

**Comment by szepeviktor** [comment]
My recipe for developer teams.

1. [proper](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/proper.php) PHP code
1. syntax check in CI
1. follow a coding standard
1. run static analysis
1. Done!

**Comment by szepeviktor** [comment]
> Out of curiosity, are you running phpstan automatically on all recently published packagist packages?

Oh YESS!

**Comment by BenMorel** [comment]
You must be having fun ;-)

**Comment by szepeviktor** [comment]
> I'm not sure why phpstan says this, I'm not expecting _unexpected_ data, but any of two well-defined types.

@phpstan shows an error as PHPDoc is a constrain on variable type and the **same** check is done with 2 `if`-s. So:

1. use `mixed`
1. or remove the 2 `if`-s because phpstan will tell you when a non-string && non-resource value is coming your way

**Comment by BenMorel** [comment]
I guess this assumes that every project *using* the library uses phpstan, **and** that phpstan is able to *always* infer the type of every variable (good luck to people using arbitrary data in arrays etc.)

These are two weak assumptions IMO.

So, no thank you, I prefer to stick to proper, developer-friendly *and* static analyser-friendly<sup>*</sup> type-hinting + actual verification in my code to mimic PHP's internal type-hint checking mechanism, and throw the `TypeError` that PHP itself *will* throw if the type is not one of those expected, once the union types RFC has been accepted.

Not doing these checks could lead to arbitrary data being passed, and hard-to-track bugs.

<sup>* Not everyone uses phpstan, and I guess other static analysis tools (PHPStorm inspections?) actually make good use of the documented types.</sup>

**Comment by szepeviktor** [comment]
I see.
